
name: CI

on:
  issues:
     types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github Context
        run: echo '${{ echo toJSON(github.event)}}' | jq
        shell: bash

